exclude: (.*/thirdparty/.*)

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v2.5.2
  hooks:
    - id: stylua
- repo: https://github.com/crate-ci/typos
  rev: v1.47.0
  hooks:
    - id: typos
- repo: local
  hooks:
  -   id: selene (awesome)
      name: selene (awesome)
      entry: selene
      args: [--config=awesome/.config/awesome/selene.toml]
      language: system
      types: [lua]
      files: ^awesome.*$
- repo: local
  hooks:
  -   id: selene (nvim)
      name: selene (nvim)
      entry: selene
      args: [--config=nvim/.config/nvim/selene.toml]
      language: system
      types: [lua]
      files: ^nvim.*$
