backend = "glx"

blur: {
    method = "dual_kawase";
};

rules: ({
    match = "name != 'Alacritty'";
    blur-background = false;
    shadow = false; fade = false; corner-radius = 0;
});

# chromium --wm-window-animations-disabled --animation-duration-scale=0
