backend = "glx"

blur: {
    method = "dual_kawase";
    strength = 3;
    noise-radius = 20;
    noise-scale = 0.5;
};

rules: ({
    match = "name != 'Alacritty' && class_i != 'org.pwmt.zathura'";
    blur-background = false;
    shadow = false; fade = false; corner-radius = 0;
});

# chromium --wm-window-animations-disabled --animation-duration-scale=0
