local mason2lsp = {
    ["clangd"] = "clangd",
    ["codelldb"] = nil,
    ["css-lsp"] = "cssls",
    ["debugpy"] = nil,
    ["docker-compose-language-service"] = "docker_compose_language_service",
    ["docker-language-server"] = "docker_language_server",
    ["eslint-lsp"] = "eslint",
    ["gh-actions-language-server"] = "gh_actions_ls",
    ["gopls"] = "gopls",
    ["json-lsp"] = "jsonls",
    ["just-lsp"] = "just",
    ["lua-language-server"] = "lua_ls",
    ["oxfmt"] = "oxfmt",
    ["oxlint"] = "oxlint",
    ["pyright"] = "pyright",
    ["ruff"] = "ruff",
    ["rust-analyzer"] = "rust_analyzer",
    ["stylua"] = "stylua",
    ["tailwindcss-language-server"] = "tailwindcss",
    ["typescript-language-server"] = "ts_ls",
    ["typos-lsp"] = "typos_lsp",
    ["vue-language-server"] = "vue_ls",
    ["yaml-language-server"] = "yamlls",
    ["zls"] = "zls",
}

local treesitter = {
    "asm",
    "bash",
    "c",
    "c_sharp",
    "cmake",
    "cpp",
    "css",
    "devicetree",
    "diff",
    "git_commit",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "gomod",
    "gosum",
    "html",
    "java",
    "javascript",
    "jsdoc",
    "json",
    "just",
    "kconfig",
    "kotlin",
    "latex",
    "lua",
    "make",
    "markdown",
    "nasm",
    "nginx",
    "python",
    "r",
    "requirements",
    "robot",
    "ron",
    "rst",
    "rust",
    "scss",
    "ssh_config",
    "svelte",
    "tmux",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vue",
    "xml",
    "yaml",
    "zig",
    "zsh",
}

local mason = vim.tbl_keys(mason2lsp)
local lsp = vim.iter(vim.tbl_values(mason2lsp))
    :filter(function(lsp_name)
        return lsp_name ~= nil
    end)
    :totable()

return {
    mason = mason,
    lsp = lsp,
    treesitter = treesitter,
}
