name: CI Workflow
on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          curl https://github.com/Kampfkarren/selene/releases/download/0.31.0/selene-0.31.0-linux.zip -L -O
          unzip selene-0.31.0-linux.zip
          chmod +x selene
          echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
      - uses: pre-commit/action@v3.0.1
